apiVersion: v1
kind: PersistentVolume
metadata:
  name: petclinic-src-pv
  labels:
    type: local
    app: webapp
spec:
  storageClassName: standard
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/petclinic/src/main/java"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: standard
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/petclinic/src/main/resources/db/mysql"