apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-pvc
spec:
  storageClassName: classtorage
  resources:
    requests: 
      storage: 256Mi
  accessModes:
    - ReadWriteOnce