apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-src-pvc
  labels:
    type: local
    app: webapp
spec:
  storageClassName: standard
  resources:
    requests: 
      storage: 600Mi
  accessModes:
    - ReadWriteOnce
  selector: 
    matchLabels:
      app: webapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  labels:
    type: local
    app: db
spec:
  storageClassName: standard
  resources:
    requests: 
      storage: 256Mi
  accessModes:
    - ReadWriteOnce
  selector: 
    matchLabels:
      app: db